# Generated by Django 3.1.7 on 2021-06-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('imagem', models.ImageField(blank=True, upload_to='imagens')),
                ('poder', models.CharField(max_length=50)),
            ],
        ),
    ]
